python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master acls-kept-in-maintainer-record > acls-kept-in-maintainer-record.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master add_folders_to_backend > add_folders_to_backend.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master bugfix-folder-returns-id-only > bugfix-folder-returns-id-only.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master clean-up-persona > clean-up-persona.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master coherent_run_command > coherent_run_command.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master combinedBackendProto > combinedBackendProto.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master cookiesession-fixes > cookiesession-fixes.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master couple_with_backbone > couple_with_backbone.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master dbchanges > dbchanges.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master dbsession-fixes > dbsession-fixes.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master fake-user-header-in-wsgi > fake-user-header-in-wsgi.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master file-uploader > file-uploader.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master fix-restrest > fix-restrest.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master http-exception-handling > http-exception-handling.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master improve_dbsession_mgmt > improve_dbsession_mgmt.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master jasmine-coupling > jasmine-coupling.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master jasmine-workspace > jasmine-workspace.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master license-and-docs > license-and-docs.res

python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master newWorkspace > newWorkspace.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master paul_standalonesvr > paul_standalonesvr.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master pseudomaster > pseudomaster.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master repoze-openid > repoze-openid.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master routing-for-urlmap > routing-for-urlmap.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master save-delete > save-delete.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master set_date_modified > set_date_modified.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master testmaster > testmaster.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master update_install_instructions > update_install_instructions.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master urlmap1 > urlmap1.res
python git_branch_watcher.py /usr/home/pbrian/src/public/Connexions/rhaptos2.repo/rhaptos2/repo master user-and-identity > user-and-identity.res
